# Generated by Django 6.1 on 2026-08-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage_experience_project_service_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Jayalakshmi Subramanian', max_length=100),
        ),
    ]
