# Generated by Django 6.1 on 2026-08-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(default='', upload_to='profile/'),
            preserve_default=False,
        ),
    ]
